name: AsyncAPI documents processing

on:
  push:
    tags:
      - 'v*'

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      #Check out repo at the created tag
      - name: Get tag name
        id: get_tag_name
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          ref: ${{ steps.get_tag_name.outputs.VERSION }}

      #Using another action for AsyncAPI for validation
      - name: Validating AsyncAPI document
        uses: WaleedAshraf/asyncapi-github-action@v0.0.9
        with:
          filepath: src/main/asyncapi/network_survey_messaging.yaml

      #In case you do not want to use defaults, you for example want to use different template
      - name: Generating HTML from my AsyncAPI document
        uses: docker://asyncapi/github-action-for-generator:2.1.7
        with:
          template: '@asyncapi/html-template@0.28.1'  #In case of template from npm, because of @ it must be in quotes
          filepath: src/main/asyncapi/network_survey_messaging.yaml
          #parameters: baseHref=/test-experiment/ sidebarOrganization=byTags #space separated list of key/values
          output: generated-html

      #Using another action that takes generated HTML and pushes it to GH Pages
      - name: Deploy GH page
        uses: JamesIves/github-pages-deploy-action@3.4.2
        with:
          ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: generated-html
